- name: Download go tar file
  command: wget https://go.dev/dl/go1.24.1.linux-amd64.tar.gz
 
- name: Delete previous installation
  command: rm -rf /usr/local/go
  become: true

- name: Extract and move new go folder to /usr/local
  command: tar -C /usr/local -xzf go1.24.1.linux-amd64.tar.gz
  become: true

- name: Change ownership of /usr/local/go
  file:
    owner: "{{ ansible_user_id }}"
    path: /usr/local/go/bin
  become: true

- name: Delete downloaded tar file
  shell: rm -rf go1.24.1.linux-amd64.tar.gz*

- name: Add go symlink to /usr/local/bin
  ansible.builtin.file:
    path: /usr/local/bin/go
    src: /usr/local/go/bin/go
    state: link
  become: true