---
- include_tasks: install-go.yml
- include_tasks: packages.yml
- include_tasks: go-programs.yml
- include_tasks: rust-tools.yml
- include_tasks: github-repos.yml
- include_tasks: python-tools.yml
- include_tasks: gem-tools.yml
# - include_tasks: bloodhound.yml
- include_tasks: msf.yml
- include_tasks: burpsuite.yml
- include_tasks: gdb.yml